### PR TITLE
Automatic docs build

### LINKED ISSUE #20: Automate building docs
### Is your feature request related to a problem? Please describe.

This project contains auto-generated API documentation that needs to be triggered manually by the contributors every time they make a change to the codebase.

As seen on https://github.com/vmware-labs/ml-conversational-analytic-tool/pull/11#pullrequestreview-832074314, the current process makes pull requests difficult to review. 

### Describe the solution you'd like

Possible solution
- Leverage GitHub actions to trigger doc update when a PR is merged

### Describe alternatives you've considered

- pdocs can also be replaced with another doc tool if there are any appropriate 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by sechkova**
Fixes #20 

Use gh actions to automatically generate the html API docs and add a new commit to the repository on each pull request.

- Add docs build environment to tox: Use tox to generate the project documentation in an isolated and reproducible environment.
- Add index.html with redirect: In order to use GitHub pages to automatically generate documentation from docs, an index file is needed in the root dir. However pdoc generates automatically the index file inside the docs/mcat dir. Add docs/index.html with a simple redirect to docs/mcat/index.html.
- Add docs build to the CI: Add a new gh actions workflow to automatically build the docs and push them to the repository on each push to main.

### CODE REVIEW

**Comment by sechkova** [comment]
Since the automatic build and push of the docs happen on push to main and cannot be seen here, I tested it on my fork and it looks like this: https://github.com/sechkova/ml-conversational-analytic-tool/commits/main

This repository could have more restrictions however and the push could fail.

**Review by tzstoyanov — APPROVED** [review]

**Comment by annajung** [comment]
just as a reminder, after the PR is merged, we would have to enable github pages for the repo.

I checked the repo setting and we do require signed commits. Could you test out what happens if you enable a signed commit requirement for your forked repo and test out what happens with the workflow there?

**Comment by sechkova** [comment]
> I checked the repo setting and we do require signed commits. Could you test out what happens if you enable a signed commit requirement for your forked repo and test out what happens with the workflow there?

@annajung I guess as expected, the commit is declined.

`remote: error: GH006: Protected branch update failed for refs/heads/main. `

 If we want to move forward the idea of an automatic commit, I'll check if it is possible to sign it in a GH Action. I'm not sure who should be the GPG key "owner" though.

Here is the full log:
```
Run git config --global user.name 'GitHub Actions'
[13](https://github.com/sechkova/ml-conversational-analytic-tool/runs/5662812744?check_suite_focus=true#step:6:13)
[main 5c4d9e3] Build docs
[14](https://github.com/sechkova/ml-conversational-analytic-tool/runs/5662812744?check_suite_focus=true#step:6:14)
 1 file changed, 4 insertions(+), 1 deletion(-)
[16](https://github.com/sechkova/ml-conversational-analytic-tool/runs/5662812744?check_suite_focus=true#step:6:16)
remote: error: GH006: Protected branch update failed for refs/heads/main.        
[17](https://github.com/sechkova/ml-conversational-analytic-tool/runs/5662812744?check_suite_focus=true#step:6:17)
remote: error: Commits must have valid signatures.        
[18](https://github.com/sechkova/ml-conversational-analytic-tool/runs/5662812744?check_suite_focus=true#step:6:18)
To https://github.com/sechkova/ml-conversational-analytic-tool
[19](https://github.com/sechkova/ml-conversational-analytic-tool/runs/5662812744?check_suite_focus=true#step:6:19)
 ! [remote rejected] main -> main (protected branch hook declined)
[20](https://github.com/sechkova/ml-conversational-analytic-tool/runs/5662812744?check_suite_focus=true#step:6:20)
error: failed to push some refs to 'https://github.com/sechkova/ml-conversational-analytic-tool'
[21](https://github.com/sechkova/ml-conversational-analytic-tool/runs/5662812744?check_suite_focus=true#step:6:21)
Error: Process completed with exit code 1.
```

**Comment by sechkova** [comment]
After checking the potential solututions, trying to surpass the brach protections tules by finding a way for a bot to sign the commits and sharing GPG keys as secrets sounds like an overkill for mcat, and also maybe raises some concerns.

I have this new idea, I modified the workflow to only check for uncommitted changes after building the docs and fail. This way there is a visible mark in the PR of a failure and the PR author can rebuild and commit the docs before merging.

@annajung what do you think?

**Comment by annajung** [comment]
Closing to clean up for deprecation

**Pull request closed without merging**
