### PR TITLE
Add CIE project

### PR DESCRIPTION
**Pull request by olga-kondr**
CIE project has .pdf document that includes project's overview and describes how to run it.

### CODE REVIEW

**Review by annajung — CHANGES_REQUESTED** [review]
hi @olga-kondr can you please clean up hardcoded secrets and force push instead of making a new commit?

**Review by difince — COMMENTED** [review]
Thank you for contributing. 
It is not good practice to upload secret keys. But overall LGTM

**Comment by difince** [comment]
@olga-kondr Thank you for contributing the flaskr/models

**Comment by annajung** [comment]
This lgtm, will leave approval to someone else! thanks @olga-kondr

**Comment by sechkova** [comment]
It needs a couple of tweaks to be able to run out of the box but otherwise looks ok. I guess they can be handled later.

**Comment by difince** [comment]
LGTM

**Review by difince — APPROVED** [review]

**Review by annajung — APPROVED** [review]

**Pull request merged**
